# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Camekan.Client

    strategy:
      matrix:
        node-version: [22]
        # Angular 21 wants CLI Node^20.19 ||| ^22.12 ||| >=24. There is Node 20.20.2 in the local. Node 22 (LTS) will be used in CI.
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Camekan.Client/package-lock.json
    - run: npm ci
    - run: cp src/environments/stripe-key.example.ts src/environments/stripe-key.ts
    - run: npm run lint
    - run: npm run build
  label-hotfix:
    if: contains(github.head_ref, 'hotfix')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label hotfix PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -f "labels[]=bug"